default:
  image: harbor.protontech.ch/android-shared/docker-android/oci:v2.1.1
  tags:
    - shared-small

variables:
  # Use fastzip to improve cache times
  #FF_USE_FASTZIP: "true"
  # Use no compression for artifacts
  ARTIFACT_COMPRESSION_LEVEL: "fastest"
  ATLAS_DEPLOY_ENV: "true"
  IMAGES: $IMAGES
  PUBLISH_APK_NAME: "ProtonDrive-Android.apk"

workflow:
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
    - if: $CI_PIPELINE_SOURCE == "schedule"
    - if: $CI_PIPELINE_SOURCE == "web"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    # Support other projects triggering our pipeline
    - if: $CI_PIPELINE_SOURCE == "pipeline"

before_script:
  # We must keep these variables here. We can't do it inside the entrypoint, as idk how but
  # gitlab is going to convert them as a variable content instead of a variable file...
  - if [[ -f /load-env.sh ]]; then source /load-env.sh; fi
  - base64 -d - < "$PROTON_KEYSTORE_FILE" > app/protonkey.jks
  - base64 -d - < "$SERVICE_ACCOUNT_FILE" > app/service_account.json
  - md5sum app/protonkey.jks
  - md5sum app/service_account.json
  - git fetch --tags
  - if [[ $CI_COMMIT_REF_NAME == "candidate" ]]; then git fetch --unshallow origin HEAD; fi

stages:
  - screenshots
  - i18n
  - prepare
  - analyze
  - deploy
  - build
  - startReview
  - test
  - report
  - publish
  - cleanup

include:
  - local: ".gitlab/*.yml"
    rules:
      - if: $TRIGGER_REASON == "drive-cross-client"
        when: never
      - when: always

  - local: "/.gitlab/cross-client/android_ui_cross_client.yml"
    rules:
      - if: $TRIGGER_REASON == "drive-cross-client"
        when: always
      - when: never
