/*
 * Copyright (c) 2025 Proton AG.
 * This file is part of Proton Drive.
 *
 * Proton Drive is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Proton Drive is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Proton Drive.  If not, see <https://www.gnu.org/licenses/>.
 */

package me.proton.android.drive.photos.presentation.extension

import android.content.res.Resources
import io.mockk.every
import io.mockk.mockk
import me.proton.android.drive.photos.presentation.state.PhotosItem
import me.proton.android.drive.photos.presentation.viewmodel.SeparatorFormatter
import me.proton.core.domain.entity.UserId
import me.proton.core.drive.base.domain.entity.FastScrollAnchor
import me.proton.core.drive.base.domain.entity.TimestampMs
import me.proton.core.drive.base.domain.entity.TimestampS
import me.proton.core.drive.base.domain.entity.toTimestampS
import me.proton.core.drive.link.domain.entity.FileId
import me.proton.core.drive.share.domain.entity.ShareId
import me.proton.core.test.kotlin.assertEquals
import org.junit.Before
import org.junit.Test
import org.junit.runner.RunWith
import org.junit.runners.Parameterized
import java.time.LocalDate
import java.time.ZoneOffset
import java.util.Locale
import me.proton.core.drive.i18n.R as I18N

@RunWith(Parameterized::class)
class GetFastScrollAnchorsTest(
    private val input: List<Triple<Int, Int, Int>>,
    private val expectedFastScrollAnchors: List<FastScrollAnchor>,
    private val anchorsInLabel: Int,
) {
    private val now = TimestampMs(1748851977000L)
    private lateinit var presenter: SeparatorFormatter
    private lateinit var getLabel: (TimestampS) -> String

    @Before
    fun setUp() {
        val resources = mockk<Resources>()
        every { resources.getString(I18N.string.photos_separator_current_month) } returns "This month"
        presenter = SeparatorFormatter(
            resources = resources,
            clock = { now.value },
            locale = Locale.US,
        )
        val labelFormatter = SeparatorFormatter(
            resources = resources,
            clock = { Long.MAX_VALUE },
            locale = Locale.US,
        )
        getLabel = { captureTime ->
            labelFormatter.toSeparator(captureTime)
        }
    }

    @Test
    fun `compare expected and actual fast scroll anchors`() {
        var photoListingIndex = 0
        val items: List<PhotosItem> = input.map {
            listOf(
                getSeparator(it.first, it.second),
                *(1..it.third).map {
                    getPhotoListing(photoListingIndex++)
                }.toTypedArray()
            )
        }.flatten()
        val actual = items.getFastScrollAnchors(
            anchors = expectedFastScrollAnchors.size,
            anchorsInLabel = anchorsInLabel,
            getLabel = getLabel,
        )
        actual.forEach { fastScrollAnchor ->
            println(
                listOf(
                    "FastScrollAnchor(scrollToPosition=${fastScrollAnchor.scrollToPosition}",
                    fastScrollAnchor.label?.let { "label=\"$it\"" } ?: "label=null",
                    "${fastScrollAnchor.dragLabel?.let { "dragLabel=\"$it\"" } ?: "dragLabel=null"}),"
                ).joinToString()
            )
        }

        assertListEquals(
            expectedFastScrollAnchors,
            actual,
        )
    }

    private fun assertListEquals(expected: List<FastScrollAnchor>, actual: List<FastScrollAnchor>) {
        assertEquals(expected.size, actual.size) { "size" }
        expected.forEachIndexed { index, expectedFastScrollAnchor ->
            assertEquals(expectedFastScrollAnchor.scrollToPosition, actual[index].scrollToPosition) { "scrollToPosition" }
            assertEquals(expectedFastScrollAnchor.label, actual[index].label) { "label" }
            assertEquals(expectedFastScrollAnchor.dragLabel, actual[index].dragLabel) { "dragLabel" }
        }
    }



    private fun getSeparator(year: Int, month: Int): PhotosItem =
        PhotosItem.Separator(
            value = presenter.toSeparator(
                TimestampMs(
                    LocalDate.of(year, month, 1)
                        .atStartOfDay()
                        .toInstant(ZoneOffset.UTC)
                        .toEpochMilli()
                ).toTimestampS()
            ),
            year = year,
            month = month,
            afterCaptureTime = TimestampMs(
                LocalDate.of(year, month, 1)
                    .atStartOfDay()
                    .toInstant(ZoneOffset.UTC)
                    .toEpochMilli()
            ).toTimestampS(),
        )

    private fun getPhotoListing(index: Int): PhotosItem =
        PhotosItem.PhotoListing(
            id = FileId(ShareId(UserId("user-id"),"share-id"), "file-id-$index"),
            captureTime = TimestampS(now.value - index),
            link = null,
        )

    companion object {
        @JvmStatic
        @Parameterized.Parameters
        fun data(): Collection<Array<Any>> = listOf(
            arrayOf(
                listOf(
                    Triple(2025, 1, 10000),
                ),
                listOf(
                    FastScrollAnchor(scrollToPosition=0, label="2025", dragLabel="January 2025"),
                    FastScrollAnchor(scrollToPosition=84, label=null, dragLabel="January 2025"),
                    FastScrollAnchor(scrollToPosition=168, label=null, dragLabel="January 2025"),
                    FastScrollAnchor(scrollToPosition=252, label=null, dragLabel="January 2025"),
                    FastScrollAnchor(scrollToPosition=336, label=null, dragLabel="January 2025"),
                    FastScrollAnchor(scrollToPosition=420, label=null, dragLabel="January 2025"),
                    FastScrollAnchor(scrollToPosition=504, label=null, dragLabel="January 2025"),
                    FastScrollAnchor(scrollToPosition=588, label=null, dragLabel="January 2025"),
                    FastScrollAnchor(scrollToPosition=672, label=null, dragLabel="January 2025"),
                    FastScrollAnchor(scrollToPosition=756, label=null, dragLabel="January 2025"),
                    FastScrollAnchor(scrollToPosition=840, label=null, dragLabel="January 2025"),
                    FastScrollAnchor(scrollToPosition=924, label=null, dragLabel="January 2025"),
                    FastScrollAnchor(scrollToPosition=1008, label=null, dragLabel="January 2025"),
                    FastScrollAnchor(scrollToPosition=1092, label=null, dragLabel="January 2025"),
                    FastScrollAnchor(scrollToPosition=1176, label=null, dragLabel="January 2025"),
                    FastScrollAnchor(scrollToPosition=1260, label=null, dragLabel="January 2025"),
                    FastScrollAnchor(scrollToPosition=1344, label=null, dragLabel="January 2025"),
                    FastScrollAnchor(scrollToPosition=1428, label=null, dragLabel="January 2025"),
                    FastScrollAnchor(scrollToPosition=1512, label=null, dragLabel="January 2025"),
                    FastScrollAnchor(scrollToPosition=1596, label=null, dragLabel="January 2025"),
                    FastScrollAnchor(scrollToPosition=1680, label=null, dragLabel="January 2025"),
                    FastScrollAnchor(scrollToPosition=1764, label=null, dragLabel="January 2025"),
                    FastScrollAnchor(scrollToPosition=1848, label=null, dragLabel="January 2025"),
                    FastScrollAnchor(scrollToPosition=1932, label=null, dragLabel="January 2025"),
                    FastScrollAnchor(scrollToPosition=2017, label=null, dragLabel="January 2025"),
                    FastScrollAnchor(scrollToPosition=2101, label=null, dragLabel="January 2025"),
                    FastScrollAnchor(scrollToPosition=2185, label=null, dragLabel="January 2025"),
                    FastScrollAnchor(scrollToPosition=2269, label=null, dragLabel="January 2025"),
                    FastScrollAnchor(scrollToPosition=2353, label=null, dragLabel="January 2025"),
                    FastScrollAnchor(scrollToPosition=2437, label=null, dragLabel="January 2025"),
                    FastScrollAnchor(scrollToPosition=2521, label=null, dragLabel="January 2025"),
                    FastScrollAnchor(scrollToPosition=2605, label=null, dragLabel="January 2025"),
                    FastScrollAnchor(scrollToPosition=2689, label=null, dragLabel="January 2025"),
                    FastScrollAnchor(scrollToPosition=2773, label=null, dragLabel="January 2025"),
                    FastScrollAnchor(scrollToPosition=2857, label=null, dragLabel="January 2025"),
                    FastScrollAnchor(scrollToPosition=2941, label=null, dragLabel="January 2025"),
                    FastScrollAnchor(scrollToPosition=3025, label=null, dragLabel="January 2025"),
                    FastScrollAnchor(scrollToPosition=3109, label=null, dragLabel="January 2025"),
                    FastScrollAnchor(scrollToPosition=3193, label=null, dragLabel="January 2025"),
                    FastScrollAnchor(scrollToPosition=3277, label=null, dragLabel="January 2025"),
                    FastScrollAnchor(scrollToPosition=3361, label=null, dragLabel="January 2025"),
                    FastScrollAnchor(scrollToPosition=3445, label=null, dragLabel="January 2025"),
                    FastScrollAnchor(scrollToPosition=3529, label=null, dragLabel="January 2025"),
                    FastScrollAnchor(scrollToPosition=3613, label=null, dragLabel="January 2025"),
                    FastScrollAnchor(scrollToPosition=3697, label=null, dragLabel="January 2025"),
                    FastScrollAnchor(scrollToPosition=3781, label=null, dragLabel="January 2025"),
                    FastScrollAnchor(scrollToPosition=3865, label=null, dragLabel="January 2025"),
                    FastScrollAnchor(scrollToPosition=3949, label=null, dragLabel="January 2025"),
                    FastScrollAnchor(scrollToPosition=4034, label=null, dragLabel="January 2025"),
                    FastScrollAnchor(scrollToPosition=4118, label=null, dragLabel="January 2025"),
                    FastScrollAnchor(scrollToPosition=4202, label=null, dragLabel="January 2025"),
                    FastScrollAnchor(scrollToPosition=4286, label=null, dragLabel="January 2025"),
                    FastScrollAnchor(scrollToPosition=4370, label=null, dragLabel="January 2025"),
                    FastScrollAnchor(scrollToPosition=4454, label=null, dragLabel="January 2025"),
                    FastScrollAnchor(scrollToPosition=4538, label=null, dragLabel="January 2025"),
                    FastScrollAnchor(scrollToPosition=4622, label=null, dragLabel="January 2025"),
                    FastScrollAnchor(scrollToPosition=4706, label=null, dragLabel="January 2025"),
                    FastScrollAnchor(scrollToPosition=4790, label=null, dragLabel="January 2025"),
                    FastScrollAnchor(scrollToPosition=4874, label=null, dragLabel="January 2025"),
                    FastScrollAnchor(scrollToPosition=4958, label=null, dragLabel="January 2025"),
                    FastScrollAnchor(scrollToPosition=5042, label=null, dragLabel="January 2025"),
                    FastScrollAnchor(scrollToPosition=5126, label=null, dragLabel="January 2025"),
                    FastScrollAnchor(scrollToPosition=5210, label=null, dragLabel="January 2025"),
                    FastScrollAnchor(scrollToPosition=5294, label=null, dragLabel="January 2025"),
                    FastScrollAnchor(scrollToPosition=5378, label=null, dragLabel="January 2025"),
                    FastScrollAnchor(scrollToPosition=5462, label=null, dragLabel="January 2025"),
                    FastScrollAnchor(scrollToPosition=5546, label=null, dragLabel="January 2025"),
                    FastScrollAnchor(scrollToPosition=5630, label=null, dragLabel="January 2025"),
                    FastScrollAnchor(scrollToPosition=5714, label=null, dragLabel="January 2025"),
                    FastScrollAnchor(scrollToPosition=5798, label=null, dragLabel="January 2025"),
                    FastScrollAnchor(scrollToPosition=5882, label=null, dragLabel="January 2025"),
                    FastScrollAnchor(scrollToPosition=5966, label=null, dragLabel="January 2025"),
                    FastScrollAnchor(scrollToPosition=6051, label=null, dragLabel="January 2025"),
                    FastScrollAnchor(scrollToPosition=6135, label=null, dragLabel="January 2025"),
                    FastScrollAnchor(scrollToPosition=6219, label=null, dragLabel="January 2025"),
                    FastScrollAnchor(scrollToPosition=6303, label=null, dragLabel="January 2025"),
                    FastScrollAnchor(scrollToPosition=6387, label=null, dragLabel="January 2025"),
                    FastScrollAnchor(scrollToPosition=6471, label=null, dragLabel="January 2025"),
                    FastScrollAnchor(scrollToPosition=6555, label=null, dragLabel="January 2025"),
                    FastScrollAnchor(scrollToPosition=6639, label=null, dragLabel="January 2025"),
                    FastScrollAnchor(scrollToPosition=6723, label=null, dragLabel="January 2025"),
                    FastScrollAnchor(scrollToPosition=6807, label=null, dragLabel="January 2025"),
                    FastScrollAnchor(scrollToPosition=6891, label=null, dragLabel="January 2025"),
                    FastScrollAnchor(scrollToPosition=6975, label=null, dragLabel="January 2025"),
                    FastScrollAnchor(scrollToPosition=7059, label=null, dragLabel="January 2025"),
                    FastScrollAnchor(scrollToPosition=7143, label=null, dragLabel="January 2025"),
                    FastScrollAnchor(scrollToPosition=7227, label=null, dragLabel="January 2025"),
                    FastScrollAnchor(scrollToPosition=7311, label=null, dragLabel="January 2025"),
                    FastScrollAnchor(scrollToPosition=7395, label=null, dragLabel="January 2025"),
                    FastScrollAnchor(scrollToPosition=7479, label=null, dragLabel="January 2025"),
                    FastScrollAnchor(scrollToPosition=7563, label=null, dragLabel="January 2025"),
                    FastScrollAnchor(scrollToPosition=7647, label=null, dragLabel="January 2025"),
                    FastScrollAnchor(scrollToPosition=7731, label=null, dragLabel="January 2025"),
                    FastScrollAnchor(scrollToPosition=7815, label=null, dragLabel="January 2025"),
                    FastScrollAnchor(scrollToPosition=7899, label=null, dragLabel="January 2025"),
                    FastScrollAnchor(scrollToPosition=7983, label=null, dragLabel="January 2025"),
                    FastScrollAnchor(scrollToPosition=8068, label=null, dragLabel="January 2025"),
                    FastScrollAnchor(scrollToPosition=8152, label=null, dragLabel="January 2025"),
                    FastScrollAnchor(scrollToPosition=8236, label=null, dragLabel="January 2025"),
                    FastScrollAnchor(scrollToPosition=8320, label=null, dragLabel="January 2025"),
                    FastScrollAnchor(scrollToPosition=8404, label=null, dragLabel="January 2025"),
                    FastScrollAnchor(scrollToPosition=8488, label=null, dragLabel="January 2025"),
                    FastScrollAnchor(scrollToPosition=8572, label=null, dragLabel="January 2025"),
                    FastScrollAnchor(scrollToPosition=8656, label=null, dragLabel="January 2025"),
                    FastScrollAnchor(scrollToPosition=8740, label=null, dragLabel="January 2025"),
                    FastScrollAnchor(scrollToPosition=8824, label=null, dragLabel="January 2025"),
                    FastScrollAnchor(scrollToPosition=8908, label=null, dragLabel="January 2025"),
                    FastScrollAnchor(scrollToPosition=8992, label=null, dragLabel="January 2025"),
                    FastScrollAnchor(scrollToPosition=9076, label=null, dragLabel="January 2025"),
                    FastScrollAnchor(scrollToPosition=9160, label=null, dragLabel="January 2025"),
                    FastScrollAnchor(scrollToPosition=9244, label=null, dragLabel="January 2025"),
                    FastScrollAnchor(scrollToPosition=9328, label=null, dragLabel="January 2025"),
                    FastScrollAnchor(scrollToPosition=9412, label=null, dragLabel="January 2025"),
                    FastScrollAnchor(scrollToPosition=9496, label=null, dragLabel="January 2025"),
                    FastScrollAnchor(scrollToPosition=9580, label=null, dragLabel="January 2025"),
                    FastScrollAnchor(scrollToPosition=9664, label=null, dragLabel="January 2025"),
                    FastScrollAnchor(scrollToPosition=9748, label=null, dragLabel="January 2025"),
                    FastScrollAnchor(scrollToPosition=9832, label=null, dragLabel="January 2025"),
                    FastScrollAnchor(scrollToPosition=9916, label=null, dragLabel="January 2025"),
                    FastScrollAnchor(scrollToPosition=10000, label=null, dragLabel="January 2025"),
                ),
                6,
            ),
            arrayOf(
                listOf(
                    Triple(2025, 1, 1),
                    Triple(2024, 1, 10),
                    Triple(2023, 1, 100),
                    Triple(2022, 1, 1),
                    Triple(2021, 1, 10),
                    Triple(2020, 1, 100),
                    Triple(2019, 1, 1),
                    Triple(2018, 1, 10),
                    Triple(2017, 1, 100),
                    Triple(2016, 1, 1),
                    Triple(2015, 1, 10),
                    Triple(2014, 1, 100),
                    Triple(2013, 1, 1),
                    Triple(2012, 1, 10),
                    Triple(2011, 1, 100),
                    Triple(2010, 1, 1),
                    Triple(2009, 1, 10),
                    Triple(2008, 1, 100),
                    Triple(2007, 1, 1),
                    Triple(2006, 1, 10),
                    Triple(2005, 1, 100),
                    Triple(2004, 1, 1),
                    Triple(2003, 1, 10),
                    Triple(2002, 1, 100),
                    Triple(2001, 1, 10),
                    Triple(2000, 1, 100),
                ),
                listOf(
                    FastScrollAnchor(scrollToPosition=0, label="2025", dragLabel="January 2025"),
                    FastScrollAnchor(scrollToPosition=2, label="2024", dragLabel="January 2024"),
                    FastScrollAnchor(scrollToPosition=13, label="2023", dragLabel="January 2023"),
                    FastScrollAnchor(scrollToPosition=114, label="2022", dragLabel="January 2022"),
                    FastScrollAnchor(scrollToPosition=116, label="2021", dragLabel="January 2021"),
                    FastScrollAnchor(scrollToPosition=127, label="2020", dragLabel="January 2020"),
                    FastScrollAnchor(scrollToPosition=228, label="2019", dragLabel="January 2019"),
                    FastScrollAnchor(scrollToPosition=230, label="2018", dragLabel="January 2018"),
                    FastScrollAnchor(scrollToPosition=241, label="2017", dragLabel="January 2017"),
                    FastScrollAnchor(scrollToPosition=342, label="2016", dragLabel="January 2016"),
                    FastScrollAnchor(scrollToPosition=344, label="2015", dragLabel="January 2015"),
                    FastScrollAnchor(scrollToPosition=355, label="2014", dragLabel="January 2014"),
                    FastScrollAnchor(scrollToPosition=456, label="2013", dragLabel="January 2013"),
                    FastScrollAnchor(scrollToPosition=458, label="2012", dragLabel="January 2012"),
                    FastScrollAnchor(scrollToPosition=469, label="2011", dragLabel="January 2011"),
                    FastScrollAnchor(scrollToPosition=570, label="2010", dragLabel="January 2010"),
                    FastScrollAnchor(scrollToPosition=572, label="2009", dragLabel="January 2009"),
                    FastScrollAnchor(scrollToPosition=583, label="2008", dragLabel="January 2008"),
                    FastScrollAnchor(scrollToPosition=684, label="2007", dragLabel="January 2007"),
                    FastScrollAnchor(scrollToPosition=686, label="2006", dragLabel="January 2006"),
                    FastScrollAnchor(scrollToPosition=1023, label=null, dragLabel="January 2000"),
                ),
                1,
            ),
            arrayOf(
                listOf(
                    Triple(2025, 6, 200),
                    Triple(2025, 5, 100),
                    Triple(2025, 4, 400),
                    Triple(2025, 2, 1000),
                    Triple(2025, 1, 300),
                    Triple(2024, 11, 150),
                    Triple(2024, 10, 20),
                    Triple(2024, 8, 810),
                    Triple(2024, 7, 1113),
                    Triple(2024, 5, 121),
                    Triple(2024, 4, 17),
                    Triple(2024, 3, 177),
                    Triple(2024, 2, 1),
                    Triple(2024, 1, 355),
                ),
                listOf(
                    FastScrollAnchor(scrollToPosition=0, label="2025", dragLabel="June 2025"),
                    FastScrollAnchor(scrollToPosition=22, label=null, dragLabel="June 2025"),
                    FastScrollAnchor(scrollToPosition=44, label=null, dragLabel="June 2025"),
                    FastScrollAnchor(scrollToPosition=67, label=null, dragLabel="June 2025"),
                    FastScrollAnchor(scrollToPosition=89, label=null, dragLabel="June 2025"),
                    FastScrollAnchor(scrollToPosition=111, label=null, dragLabel="June 2025"),
                    FastScrollAnchor(scrollToPosition=134, label=null, dragLabel="June 2025"),
                    FastScrollAnchor(scrollToPosition=156, label=null, dragLabel="June 2025"),
                    FastScrollAnchor(scrollToPosition=178, label=null, dragLabel="June 2025"),
                    FastScrollAnchor(scrollToPosition=201, label=null, dragLabel="May 2025"),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=302, label=null, dragLabel="April 2025"),
                    FastScrollAnchor(scrollToPosition=346, label=null, dragLabel="April 2025"),
                    FastScrollAnchor(scrollToPosition=391, label=null, dragLabel="April 2025"),
                    FastScrollAnchor(scrollToPosition=435, label=null, dragLabel="April 2025"),
                    FastScrollAnchor(scrollToPosition=480, label=null, dragLabel="April 2025"),
                    FastScrollAnchor(scrollToPosition=524, label=null, dragLabel="April 2025"),
                    FastScrollAnchor(scrollToPosition=569, label=null, dragLabel="April 2025"),
                    FastScrollAnchor(scrollToPosition=613, label=null, dragLabel="April 2025"),
                    FastScrollAnchor(scrollToPosition=658, label=null, dragLabel="April 2025"),
                    FastScrollAnchor(scrollToPosition=703, label=null, dragLabel="February 2025"),
                    FastScrollAnchor(scrollToPosition=814, label=null, dragLabel="February 2025"),
                    FastScrollAnchor(scrollToPosition=925, label=null, dragLabel="February 2025"),
                    FastScrollAnchor(scrollToPosition=1036, label=null, dragLabel="February 2025"),
                    FastScrollAnchor(scrollToPosition=1147, label=null, dragLabel="February 2025"),
                    FastScrollAnchor(scrollToPosition=1259, label=null, dragLabel="February 2025"),
                    FastScrollAnchor(scrollToPosition=1370, label=null, dragLabel="February 2025"),
                    FastScrollAnchor(scrollToPosition=1481, label=null, dragLabel="February 2025"),
                    FastScrollAnchor(scrollToPosition=1592, label=null, dragLabel="February 2025"),
                    FastScrollAnchor(scrollToPosition=1704, label=null, dragLabel="January 2025"),
                    FastScrollAnchor(scrollToPosition=1737, label=null, dragLabel="January 2025"),
                    FastScrollAnchor(scrollToPosition=1770, label=null, dragLabel="January 2025"),
                    FastScrollAnchor(scrollToPosition=1804, label=null, dragLabel="January 2025"),
                    FastScrollAnchor(scrollToPosition=1837, label=null, dragLabel="January 2025"),
                    FastScrollAnchor(scrollToPosition=1871, label=null, dragLabel="January 2025"),
                    FastScrollAnchor(scrollToPosition=1904, label=null, dragLabel="January 2025"),
                    FastScrollAnchor(scrollToPosition=1938, label=null, dragLabel="January 2025"),
                    FastScrollAnchor(scrollToPosition=1971, label=null, dragLabel="January 2025"),
                    FastScrollAnchor(scrollToPosition=2005, label="2024", dragLabel="November 2024"),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=2156, label=null, dragLabel="October 2024"),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=2177, label=null, dragLabel="August 2024"),
                    FastScrollAnchor(scrollToPosition=2267, label=null, dragLabel="August 2024"),
                    FastScrollAnchor(scrollToPosition=2357, label=null, dragLabel="August 2024"),
                    FastScrollAnchor(scrollToPosition=2447, label=null, dragLabel="August 2024"),
                    FastScrollAnchor(scrollToPosition=2537, label=null, dragLabel="August 2024"),
                    FastScrollAnchor(scrollToPosition=2627, label=null, dragLabel="August 2024"),
                    FastScrollAnchor(scrollToPosition=2717, label=null, dragLabel="August 2024"),
                    FastScrollAnchor(scrollToPosition=2807, label=null, dragLabel="August 2024"),
                    FastScrollAnchor(scrollToPosition=2897, label=null, dragLabel="August 2024"),
                    FastScrollAnchor(scrollToPosition=2988, label=null, dragLabel="July 2024"),
                    FastScrollAnchor(scrollToPosition=3111, label=null, dragLabel="July 2024"),
                    FastScrollAnchor(scrollToPosition=3235, label=null, dragLabel="July 2024"),
                    FastScrollAnchor(scrollToPosition=3359, label=null, dragLabel="July 2024"),
                    FastScrollAnchor(scrollToPosition=3483, label=null, dragLabel="July 2024"),
                    FastScrollAnchor(scrollToPosition=3606, label=null, dragLabel="July 2024"),
                    FastScrollAnchor(scrollToPosition=3730, label=null, dragLabel="July 2024"),
                    FastScrollAnchor(scrollToPosition=3854, label=null, dragLabel="July 2024"),
                    FastScrollAnchor(scrollToPosition=3978, label=null, dragLabel="July 2024"),
                    FastScrollAnchor(scrollToPosition=4102, label=null, dragLabel="May 2024"),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=4224, label=null, dragLabel="April 2024"),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=4242, label=null, dragLabel="March 2024"),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=4420, label=null, dragLabel="February 2024"),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=4422, label=null, dragLabel="January 2024"),
                    FastScrollAnchor(scrollToPosition=4461, label=null, dragLabel="January 2024"),
                    FastScrollAnchor(scrollToPosition=4501, label=null, dragLabel="January 2024"),
                    FastScrollAnchor(scrollToPosition=4540, label=null, dragLabel="January 2024"),
                    FastScrollAnchor(scrollToPosition=4580, label=null, dragLabel="January 2024"),
                    FastScrollAnchor(scrollToPosition=4619, label=null, dragLabel="January 2024"),
                    FastScrollAnchor(scrollToPosition=4659, label=null, dragLabel="January 2024"),
                    FastScrollAnchor(scrollToPosition=4698, label=null, dragLabel="January 2024"),
                    FastScrollAnchor(scrollToPosition=4738, label=null, dragLabel="January 2024"),
                    FastScrollAnchor(scrollToPosition=4777, label=null, dragLabel="January 2024"),
                ),
                6,
            ),
            arrayOf(
                listOf(
                    Triple(2025, 6, 200),
                    Triple(2024, 12, 200),
                    Triple(2023, 12, 200),
                    Triple(2022, 12, 200),
                    Triple(2021, 12, 200),
                    Triple(2020, 12, 200),
                    Triple(2019, 12, 200),
                    Triple(2018, 12, 200),
                    Triple(2017, 12, 200),
                    Triple(2016, 12, 200),
                    Triple(2015, 12, 200),
                    Triple(2014, 12, 200),
                    Triple(2013, 12, 200),
                    Triple(2012, 12, 200),
                    Triple(2011, 12, 200),
                    Triple(2010, 12, 200),
                ),
                listOf(
                    FastScrollAnchor(scrollToPosition=0, label="2025", dragLabel="June 2025"),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=201, label="2024", dragLabel="December 2024"),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=402, label="2023", dragLabel="December 2023"),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=603, label="2022", dragLabel="December 2022"),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=804, label="2021", dragLabel="December 2021"),
                    FastScrollAnchor(scrollToPosition=1005, label="2020", dragLabel="December 2020"),
                    FastScrollAnchor(scrollToPosition=1206, label="2019", dragLabel="December 2019"),
                    FastScrollAnchor(scrollToPosition=1407, label="2018", dragLabel="December 2018"),
                    FastScrollAnchor(scrollToPosition=1608, label="2017", dragLabel="December 2017"),
                    FastScrollAnchor(scrollToPosition=1809, label="2016", dragLabel="December 2016"),
                    FastScrollAnchor(scrollToPosition=2010, label="2015", dragLabel="December 2015"),
                    FastScrollAnchor(scrollToPosition=2211, label="2014", dragLabel="December 2014"),
                    FastScrollAnchor(scrollToPosition=2412, label="2013", dragLabel="December 2013"),
                    FastScrollAnchor(scrollToPosition=2613, label="2012", dragLabel="December 2012"),
                    FastScrollAnchor(scrollToPosition=2814, label="2011", dragLabel="December 2011"),
                    FastScrollAnchor(scrollToPosition=3015, label="2010", dragLabel="December 2010"),
                    FastScrollAnchor(scrollToPosition=3215, label=null, dragLabel="December 2010"),
                ),
                1,
            ),
            arrayOf(
                listOf(
                    Triple(2025,6,3),
                    Triple(2025,5,63),
                    Triple(2025,4,22),
                    Triple(2025,3,46),
                    Triple(2025,2,33),
                    Triple(2025,1,37),
                    Triple(2024,12,84),
                    Triple(2024,11,87),
                    Triple(2024,10,32),
                    Triple(2024,9,50),
                    Triple(2024,8,57),
                    Triple(2024,7,9),
                    Triple(2024,6,12),
                    Triple(2024,5,12),
                    Triple(2024,4,2),
                    Triple(2024,3,4),
                    Triple(2024,2,4),
                    Triple(2024,1,61),
                    Triple(2023,12,4),
                    Triple(2023,11,2),
                    Triple(2023,10,4),
                    Triple(2023,9,17),
                    Triple(2023,8,44),
                    Triple(2023,7,17),
                    Triple(2023,6,21),
                    Triple(2023,5,19),
                    Triple(2023,4,42),
                    Triple(2023,2,23),
                    Triple(2023,1,59),
                    Triple(2022,12,28),
                    Triple(2022,11,5),
                    Triple(2022,10,5),
                    Triple(2022,8,72),
                    Triple(2022,6,17),
                    Triple(2022,5,12),
                    Triple(2022,2,3),
                    Triple(2022,1,2),
                    Triple(2021,12,4),
                    Triple(2021,11,5),
                    Triple(2021,9,14),
                    Triple(2021,8,7),
                    Triple(2021,6,8),
                    Triple(2021,5,16),
                    Triple(2021,4,5),
                    Triple(2021,1,2),
                    Triple(2020,12,9),
                    Triple(2020,11,2),
                    Triple(2020,10,9),
                    Triple(2020,9,8),
                    Triple(2020,8,7),
                    Triple(2020,7,30),
                    Triple(2020,6,9),
                    Triple(2020,5,3),
                    Triple(2020,4,9),
                    Triple(2020,3,18),
                    Triple(2020,2,21),
                    Triple(2020,1,6),
                    Triple(2019,12,11),
                    Triple(2019,11,5),
                    Triple(2019,9,3),
                    Triple(2019,8,14),
                    Triple(2019,7,2),
                    Triple(2019,6,16),
                    Triple(2019,5,53),
                    Triple(2019,4,2),
                    Triple(2019,3,3),
                    Triple(2019,2,26),
                    Triple(2019,1,15),
                    Triple(2018,12,10),
                    Triple(2018,10,2),
                    Triple(2018,9,5),
                    Triple(2018,8,65),
                    Triple(2018,7,12),
                    Triple(2018,6,61),
                    Triple(2018,5,14),
                    Triple(2018,4,8),
                    Triple(2018,3,3),
                    Triple(2018,2,6),
                    Triple(2018,1,7),
                    Triple(2017,12,2),
                    Triple(2017,8,9),
                ),
                listOf(
                    FastScrollAnchor(scrollToPosition=0, label="2025", dragLabel="June 2025"),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=4, label=null, dragLabel="May 2025"),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=68, label=null, dragLabel="April 2025"),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=91, label=null, dragLabel="March 2025"),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=138, label=null, dragLabel="February 2025"),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=172, label=null, dragLabel="January 2025"),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=210, label="2024", dragLabel="December 2024"),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=295, label=null, dragLabel="November 2024"),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=383, label=null, dragLabel="October 2024"),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=416, label=null, dragLabel="September 2024"),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=467, label=null, dragLabel="August 2024"),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=525, label=null, dragLabel="July 2024"),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=535, label=null, dragLabel="June 2024"),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=548, label=null, dragLabel="May 2024"),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=561, label=null, dragLabel="April 2024"),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=564, label=null, dragLabel="March 2024"),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=569, label=null, dragLabel="February 2024"),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=574, label=null, dragLabel="January 2024"),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=636, label="2023", dragLabel="December 2023"),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=641, label=null, dragLabel="November 2023"),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=644, label=null, dragLabel="October 2023"),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=649, label=null, dragLabel="September 2023"),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=667, label=null, dragLabel="August 2023"),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=712, label=null, dragLabel="July 2023"),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=730, label=null, dragLabel="June 2023"),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=752, label=null, dragLabel="May 2023"),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=772, label=null, dragLabel="April 2023"),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=815, label=null, dragLabel="February 2023"),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=839, label=null, dragLabel="January 2023"),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=899, label="2022", dragLabel="December 2022"),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=928, label=null, dragLabel="November 2022"),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=934, label=null, dragLabel="October 2022"),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=940, label=null, dragLabel="August 2022"),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=1013, label=null, dragLabel="June 2022"),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=1031, label=null, dragLabel="May 2022"),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=1044, label=null, dragLabel="February 2022"),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=1048, label=null, dragLabel="January 2022"),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=1051, label="2021", dragLabel="December 2021"),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=1056, label=null, dragLabel="November 2021"),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=1062, label=null, dragLabel="September 2021"),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=1077, label=null, dragLabel="August 2021"),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=1085, label=null, dragLabel="June 2021"),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=1094, label=null, dragLabel="May 2021"),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=1111, label=null, dragLabel="April 2021"),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=1117, label=null, dragLabel="January 2021"),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=1120, label="2020", dragLabel="December 2020"),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=1130, label=null, dragLabel="November 2020"),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=1133, label=null, dragLabel="October 2020"),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=1143, label=null, dragLabel="September 2020"),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=1152, label=null, dragLabel="August 2020"),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=1160, label=null, dragLabel="July 2020"),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=1191, label=null, dragLabel="June 2020"),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=1201, label=null, dragLabel="May 2020"),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=1205, label=null, dragLabel="April 2020"),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=1215, label=null, dragLabel="March 2020"),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=1234, label=null, dragLabel="February 2020"),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=1256, label=null, dragLabel="January 2020"),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=1263, label="2019", dragLabel="December 2019"),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=1275, label=null, dragLabel="November 2019"),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=1281, label=null, dragLabel="September 2019"),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=1285, label=null, dragLabel="August 2019"),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=1300, label=null, dragLabel="July 2019"),
                    FastScrollAnchor(scrollToPosition=1303, label=null, dragLabel="June 2019"),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=1320, label=null, dragLabel="May 2019"),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=1374, label=null, dragLabel="April 2019"),
                    FastScrollAnchor(scrollToPosition=1377, label=null, dragLabel="March 2019"),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=1381, label=null, dragLabel="February 2019"),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=1408, label=null, dragLabel="January 2019"),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=1424, label="2018", dragLabel="December 2018"),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=1435, label=null, dragLabel="October 2018"),
                    FastScrollAnchor(scrollToPosition=1438, label=null, dragLabel="September 2018"),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=1444, label=null, dragLabel="August 2018"),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=1510, label=null, dragLabel="July 2018"),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=1523, label=null, dragLabel="June 2018"),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=1585, label=null, dragLabel="May 2018"),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=1600, label=null, dragLabel="April 2018"),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=1609, label=null, dragLabel="March 2018"),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=1613, label=null, dragLabel="February 2018"),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=1620, label=null, dragLabel="January 2018"),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=1628, label="2017", dragLabel="December 2017"),
                    FastScrollAnchor(scrollToPosition=1631, label=null, dragLabel="August 2017"),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=1640, label=null, dragLabel="August 2017"),
                ),
                6,
            ),
            arrayOf(
                listOf(
                    Triple(2025,5,41),
                    Triple(2025,1,10),
                    Triple(2024,12,6),
                    Triple(2024,10,29),
                    Triple(2024,1,232),
                    Triple(2023,12,78),
                    Triple(2023,11,76),
                    Triple(2023,10,276),
                    Triple(2023,9,198),
                    Triple(2023,8,134),
                    Triple(2023,7,515),
                    Triple(2023,6,1944),
                    Triple(2023,5,229),
                    Triple(2023,4,115),
                    Triple(2023,3,333),
                    Triple(2023,2,303),
                    Triple(2023,1,481),
                    Triple(2022,12,153),
                    Triple(2022,11,110),
                    Triple(2022,10,201),
                    Triple(2022,9,137),
                    Triple(2022,8,452),
                    Triple(2022,7,76),
                    Triple(2022,6,64),
                    Triple(2022,5,76),
                    Triple(2022,4,204),
                    Triple(2022,3,57),
                    Triple(2022,2,39),
                    Triple(2022,1,49),
                    Triple(2021,12,99),
                    Triple(2021,11,124),
                    Triple(2021,10,95),
                    Triple(2021,9,38),
                    Triple(2021,8,59),
                    Triple(2021,7,37),
                    Triple(2021,6,25),
                    Triple(2021,5,33),
                    Triple(2021,4,47),
                    Triple(2021,3,43),
                    Triple(2021,2,34),
                    Triple(2021,1,24),
                    Triple(2020,12,45),
                    Triple(2020,11,31),
                    Triple(2020,10,17),
                    Triple(2020,9,27),
                    Triple(2020,8,58),
                    Triple(2020,7,50),
                    Triple(2020,6,82),
                    Triple(2020,5,13),
                    Triple(2020,4,15),
                    Triple(2020,3,25),
                    Triple(2020,2,1),
                    Triple(2020,1,13),
                    Triple(2019,12,4),
                    Triple(2019,9,2),
                    Triple(2019,8,16),
                    Triple(2019,7,3),
                    Triple(2019,6,23),
                    Triple(2019,5,1),
                    Triple(2019,3,5),
                    Triple(2018,12,2),
                    Triple(2018,11,1),
                    Triple(2018,10,4),
                    Triple(2018,9,27),
                    Triple(2018,8,11),
                    Triple(2018,7,21),
                    Triple(2018,6,5),
                    Triple(2018,5,1),
                    Triple(2018,4,1),
                    Triple(2018,3,3),
                    Triple(2018,1,17),
                    Triple(2017,11,2),
                    Triple(2017,5,6),
                    Triple(2016,9,4),
                    Triple(2016,8,2),
                    Triple(2016,7,1),
                    Triple(2016,1,1),
                    Triple(2015,8,2),
                    Triple(2014,12,1),
                    Triple(2013,7,1),
                    Triple(2013,1,14),
                    Triple(2012,12,11),
                    Triple(2012,11,5),
                    Triple(2012,10,47),
                    Triple(2012,9,18),
                    Triple(2012,8,4),
                    Triple(2011,12,2),
                    Triple(2011,3,1),
                    Triple(2009,10,1),
                ),
                listOf(
                    FastScrollAnchor(scrollToPosition=0, label="2025", dragLabel="May 2025"),
                    FastScrollAnchor(scrollToPosition=42, label=null, dragLabel="January 2025"),
                    FastScrollAnchor(scrollToPosition=53, label=null, dragLabel="December 2024"),
                    FastScrollAnchor(scrollToPosition=60, label=null, dragLabel="October 2024"),
                    FastScrollAnchor(scrollToPosition=90, label=null, dragLabel="January 2024"),
                    FastScrollAnchor(scrollToPosition=206, label="2024", dragLabel="January 2024"),
                    FastScrollAnchor(scrollToPosition=323, label=null, dragLabel="December 2023"),
                    FastScrollAnchor(scrollToPosition=402, label=null, dragLabel="November 2023"),
                    FastScrollAnchor(scrollToPosition=479, label=null, dragLabel="October 2023"),
                    FastScrollAnchor(scrollToPosition=617, label=null, dragLabel="October 2023"),
                    FastScrollAnchor(scrollToPosition=756, label=null, dragLabel="September 2023"),
                    FastScrollAnchor(scrollToPosition=855, label="2023", dragLabel="September 2023"),
                    FastScrollAnchor(scrollToPosition=955, label=null, dragLabel="August 2023"),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=1090, label=null, dragLabel="July 2023"),
                    FastScrollAnchor(scrollToPosition=1348, label=null, dragLabel="July 2023"),
                    FastScrollAnchor(scrollToPosition=1606, label=null, dragLabel="June 2023"),
                    FastScrollAnchor(scrollToPosition=2578, label=null, dragLabel="June 2023"),
                    FastScrollAnchor(scrollToPosition=3551, label=null, dragLabel="May 2023"),
                    FastScrollAnchor(scrollToPosition=3666, label=null, dragLabel="May 2023"),
                    FastScrollAnchor(scrollToPosition=3781, label=null, dragLabel="April 2023"),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=3897, label=null, dragLabel="March 2023"),
                    FastScrollAnchor(scrollToPosition=4064, label=null, dragLabel="March 2023"),
                    FastScrollAnchor(scrollToPosition=4231, label=null, dragLabel="February 2023"),
                    FastScrollAnchor(scrollToPosition=4383, label=null, dragLabel="February 2023"),
                    FastScrollAnchor(scrollToPosition=4535, label=null, dragLabel="January 2023"),
                    FastScrollAnchor(scrollToPosition=4776, label=null, dragLabel="January 2023"),
                    FastScrollAnchor(scrollToPosition=5017, label="2022", dragLabel="December 2022"),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=5171, label=null, dragLabel="November 2022"),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=5282, label=null, dragLabel="October 2022"),
                    FastScrollAnchor(scrollToPosition=5383, label=null, dragLabel="October 2022"),
                    FastScrollAnchor(scrollToPosition=5484, label=null, dragLabel="September 2022"),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=5622, label=null, dragLabel="August 2022"),
                    FastScrollAnchor(scrollToPosition=5848, label=null, dragLabel="August 2022"),
                    FastScrollAnchor(scrollToPosition=6075, label=null, dragLabel="July 2022"),
                    FastScrollAnchor(scrollToPosition=6152, label=null, dragLabel="June 2022"),
                    FastScrollAnchor(scrollToPosition=6217, label=null, dragLabel="May 2022"),
                    FastScrollAnchor(scrollToPosition=6294, label=null, dragLabel="April 2022"),
                    FastScrollAnchor(scrollToPosition=6396, label=null, dragLabel="April 2022"),
                    FastScrollAnchor(scrollToPosition=6499, label=null, dragLabel="March 2022"),
                    FastScrollAnchor(scrollToPosition=6557, label=null, dragLabel="February 2022"),
                    FastScrollAnchor(scrollToPosition=6597, label=null, dragLabel="January 2022"),
                    FastScrollAnchor(scrollToPosition=6647, label="2021", dragLabel="December 2021"),
                    FastScrollAnchor(scrollToPosition=6747, label=null, dragLabel="November 2021"),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=6872, label=null, dragLabel="October 2021"),
                    FastScrollAnchor(scrollToPosition=6968, label=null, dragLabel="September 2021"),
                    FastScrollAnchor(scrollToPosition=7007, label=null, dragLabel="August 2021"),
                    FastScrollAnchor(scrollToPosition=7067, label=null, dragLabel="July 2021"),
                    FastScrollAnchor(scrollToPosition=7105, label=null, dragLabel="June 2021"),
                    FastScrollAnchor(scrollToPosition=7131, label=null, dragLabel="May 2021"),
                    FastScrollAnchor(scrollToPosition=7165, label=null, dragLabel="April 2021"),
                    FastScrollAnchor(scrollToPosition=7213, label=null, dragLabel="March 2021"),
                    FastScrollAnchor(scrollToPosition=7257, label=null, dragLabel="February 2021"),
                    FastScrollAnchor(scrollToPosition=7292, label=null, dragLabel="January 2021"),
                    FastScrollAnchor(scrollToPosition=7317, label="2020", dragLabel="December 2020"),
                    FastScrollAnchor(scrollToPosition=7363, label=null, dragLabel="November 2020"),
                    FastScrollAnchor(scrollToPosition=7395, label=null, dragLabel="October 2020"),
                    FastScrollAnchor(scrollToPosition=7413, label=null, dragLabel="September 2020"),
                    FastScrollAnchor(scrollToPosition=7441, label=null, dragLabel="August 2020"),
                    FastScrollAnchor(scrollToPosition=7500, label=null, dragLabel="July 2020"),
                    FastScrollAnchor(scrollToPosition=7551, label=null, dragLabel="June 2020"),
                    FastScrollAnchor(scrollToPosition=7634, label=null, dragLabel="May 2020"),
                    FastScrollAnchor(scrollToPosition=7648, label=null, dragLabel="April 2020"),
                    FastScrollAnchor(scrollToPosition=7664, label=null, dragLabel="March 2020"),
                    FastScrollAnchor(scrollToPosition=7690, label=null, dragLabel="February 2020"),
                    FastScrollAnchor(scrollToPosition=7692, label=null, dragLabel="January 2020"),
                    FastScrollAnchor(scrollToPosition=7706, label="2019", dragLabel="December 2019"),
                    FastScrollAnchor(scrollToPosition=7711, label=null, dragLabel="September 2019"),
                    FastScrollAnchor(scrollToPosition=7714, label=null, dragLabel="August 2019"),
                    FastScrollAnchor(scrollToPosition=7731, label=null, dragLabel="July 2019"),
                    FastScrollAnchor(scrollToPosition=7735, label=null, dragLabel="June 2019"),
                    FastScrollAnchor(scrollToPosition=7759, label=null, dragLabel="May 2019"),
                    FastScrollAnchor(scrollToPosition=7761, label=null, dragLabel="March 2019"),
                    FastScrollAnchor(scrollToPosition=7767, label="2018", dragLabel="December 2018"),
                    FastScrollAnchor(scrollToPosition=7770, label=null, dragLabel="November 2018"),
                    FastScrollAnchor(scrollToPosition=7772, label=null, dragLabel="October 2018"),
                    FastScrollAnchor(scrollToPosition=7777, label=null, dragLabel="September 2018"),
                    FastScrollAnchor(scrollToPosition=7805, label=null, dragLabel="August 2018"),
                    FastScrollAnchor(scrollToPosition=7817, label=null, dragLabel="July 2018"),
                    FastScrollAnchor(scrollToPosition=7839, label=null, dragLabel="June 2018"),
                    FastScrollAnchor(scrollToPosition=7845, label=null, dragLabel="May 2018"),
                    FastScrollAnchor(scrollToPosition=7847, label=null, dragLabel="April 2018"),
                    FastScrollAnchor(scrollToPosition=7849, label=null, dragLabel="March 2018"),
                    FastScrollAnchor(scrollToPosition=7853, label=null, dragLabel="January 2018"),
                    FastScrollAnchor(scrollToPosition=7871, label="2017", dragLabel="November 2017"),
                    FastScrollAnchor(scrollToPosition=7874, label=null, dragLabel="May 2017"),
                    FastScrollAnchor(scrollToPosition=7881, label=null, dragLabel="September 2016"),
                    FastScrollAnchor(scrollToPosition=7886, label=null, dragLabel="August 2016"),
                    FastScrollAnchor(scrollToPosition=7889, label=null, dragLabel="July 2016"),
                    FastScrollAnchor(scrollToPosition=7891, label=null, dragLabel="January 2016"),
                    FastScrollAnchor(scrollToPosition=7893, label="2015", dragLabel="August 2015"),
                    FastScrollAnchor(scrollToPosition=7896, label=null, dragLabel="December 2014"),
                    FastScrollAnchor(scrollToPosition=7898, label=null, dragLabel="July 2013"),
                    FastScrollAnchor(scrollToPosition=7900, label=null, dragLabel="January 2013"),
                    FastScrollAnchor(scrollToPosition=7915, label=null, dragLabel="December 2012"),
                    FastScrollAnchor(scrollToPosition=7927, label=null, dragLabel="November 2012"),
                    FastScrollAnchor(scrollToPosition=7933, label="2012", dragLabel="October 2012"),
                    FastScrollAnchor(scrollToPosition=7981, label=null, dragLabel="September 2012"),
                    FastScrollAnchor(scrollToPosition=8000, label=null, dragLabel="August 2012"),
                    FastScrollAnchor(scrollToPosition=8005, label=null, dragLabel="December 2011"),
                    FastScrollAnchor(scrollToPosition=8008, label=null, dragLabel="March 2011"),
                    FastScrollAnchor(scrollToPosition=8010, label=null, dragLabel="October 2009"),
                    FastScrollAnchor(scrollToPosition=8011, label=null, dragLabel="October 2009"),
                ),
                6,
            ),
            arrayOf(
                listOf(
                    Triple(2025,6,106),
                    Triple(2025,5,162),
                    Triple(2025,4,111),
                    Triple(2025,3,132),
                    Triple(2025,2,123),
                    Triple(2025,1,97),
                    Triple(2024,12,251),
                    Triple(2024,11,55),
                    Triple(2024,10,80),
                    Triple(2024,9,1208),
                    Triple(2024,8,116),
                    Triple(2024,7,111),
                    Triple(2024,6,336),
                    Triple(2024,5,111),
                    Triple(2024,4,2),
                    Triple(2024,3,5),
                    Triple(2024,2,6),
                    Triple(2024,1,5),
                    Triple(2023,12,4),
                    Triple(2023,11,2),
                    Triple(2023,10,273),
                    Triple(2023,6,2),
                    Triple(2023,4,11),
                    Triple(2022,10,2),
                    Triple(2022,8,1),
                    Triple(2022,4,2),
                    Triple(2022,2,1),
                    Triple(2021,10,215),
                    Triple(2021,9,113),
                    Triple(2021,8,76),
                    Triple(2021,7,90),
                    Triple(2020,11,2),
                    Triple(2020,5,298),
                    Triple(2020,2,3),
                    Triple(2019,10,2),
                    Triple(2019,9,74),
                    Triple(2019,8,2),
                    Triple(2019,7,138),
                    Triple(2018,7,197),
                    Triple(2017,11,2),
                    Triple(2017,10,4),
                    Triple(2017,7,2),
                    Triple(2017,6,2),
                    Triple(2017,3,163),
                    Triple(2017,2,74),
                    Triple(2016,12,324),
                    Triple(2016,10,50),
                    Triple(2016,9,125),
                    Triple(2016,8,66),
                    Triple(2016,7,2),
                    Triple(2016,6,2),
                    Triple(2016,3,6),
                    Triple(2014,3,4),
                    Triple(2014,1,2),
                    Triple(2013,11,2),
                    Triple(2013,3,2),
                    Triple(2013,2,2),
                    Triple(2012,12,4),
                ),
                listOf(
                    FastScrollAnchor(scrollToPosition=0, label="2025", dragLabel="June 2025"),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=107, label=null, dragLabel="May 2025"),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=270, label=null, dragLabel="April 2025"),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=382, label=null, dragLabel="March 2025"),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=515, label=null, dragLabel="February 2025"),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=639, label=null, dragLabel="January 2025"),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=737, label="2024", dragLabel="December 2024"),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=989, label=null, dragLabel="November 2024"),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=1045, label=null, dragLabel="October 2024"),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=1126, label=null, dragLabel="September 2024"),
                    FastScrollAnchor(scrollToPosition=1529, label=null, dragLabel="September 2024"),
                    FastScrollAnchor(scrollToPosition=1932, label=null, dragLabel="September 2024"),
                    FastScrollAnchor(scrollToPosition=2335, label=null, dragLabel="August 2024"),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=2452, label=null, dragLabel="July 2024"),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=2564, label=null, dragLabel="June 2024"),
                    FastScrollAnchor(scrollToPosition=2676, label=null, dragLabel="June 2024"),
                    FastScrollAnchor(scrollToPosition=2788, label=null, dragLabel="June 2024"),
                    FastScrollAnchor(scrollToPosition=2901, label=null, dragLabel="May 2024"),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=3013, label=null, dragLabel="April 2024"),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=3016, label=null, dragLabel="March 2024"),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=3022, label=null, dragLabel="February 2024"),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=3029, label=null, dragLabel="January 2024"),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=3035, label="2023", dragLabel="December 2023"),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=3040, label=null, dragLabel="November 2023"),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=3043, label=null, dragLabel="October 2023"),
                    FastScrollAnchor(scrollToPosition=3134, label=null, dragLabel="October 2023"),
                    FastScrollAnchor(scrollToPosition=3225, label=null, dragLabel="October 2023"),
                    FastScrollAnchor(scrollToPosition=3317, label=null, dragLabel="June 2023"),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=3320, label=null, dragLabel="April 2023"),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=3332, label="2022", dragLabel="October 2022"),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=3335, label=null, dragLabel="August 2022"),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=3337, label=null, dragLabel="April 2022"),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=3340, label=null, dragLabel="February 2022"),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=3342, label="2021", dragLabel="October 2021"),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=3558, label=null, dragLabel="September 2021"),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=3672, label=null, dragLabel="August 2021"),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=3749, label=null, dragLabel="July 2021"),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=3840, label="2020", dragLabel="November 2020"),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=3843, label=null, dragLabel="May 2020"),
                    FastScrollAnchor(scrollToPosition=3942, label=null, dragLabel="May 2020"),
                    FastScrollAnchor(scrollToPosition=4042, label=null, dragLabel="May 2020"),
                    FastScrollAnchor(scrollToPosition=4142, label=null, dragLabel="February 2020"),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=4146, label="2019", dragLabel="October 2019"),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=4149, label=null, dragLabel="September 2019"),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=4224, label=null, dragLabel="August 2019"),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=4227, label=null, dragLabel="July 2019"),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=4366, label="2018", dragLabel="July 2018"),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=4564, label=null, dragLabel="November 2017"),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=4567, label=null, dragLabel="October 2017"),
                    FastScrollAnchor(scrollToPosition=null, label="2017", dragLabel=null),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=4572, label=null, dragLabel="July 2017"),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=4575, label=null, dragLabel="June 2017"),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=4578, label=null, dragLabel="March 2017"),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=4742, label=null, dragLabel="February 2017"),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=4817, label="2016", dragLabel="December 2016"),
                    FastScrollAnchor(scrollToPosition=4925, label=null, dragLabel="December 2016"),
                    FastScrollAnchor(scrollToPosition=5033, label=null, dragLabel="December 2016"),
                    FastScrollAnchor(scrollToPosition=5142, label=null, dragLabel="October 2016"),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=5193, label=null, dragLabel="September 2016"),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=5319, label=null, dragLabel="August 2016"),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=5386, label=null, dragLabel="July 2016"),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=5389, label=null, dragLabel="June 2016"),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=5392, label=null, dragLabel="March 2016"),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=5399, label="2014", dragLabel="March 2014"),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=5404, label=null, dragLabel="January 2014"),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=5407, label=null, dragLabel="November 2013"),
                    FastScrollAnchor(scrollToPosition=null, label="2013", dragLabel=null),
                    FastScrollAnchor(scrollToPosition=5410, label=null, dragLabel="March 2013"),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=5413, label=null, dragLabel="February 2013"),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=5416, label=null, dragLabel="December 2012"),
                    FastScrollAnchor(scrollToPosition=null, label="2012", dragLabel=null),
                    FastScrollAnchor(scrollToPosition=null, label=null, dragLabel=null),
                    FastScrollAnchor(scrollToPosition=5420, label=null, dragLabel="December 2012"),
                ),
                6,
            ),
        )
    }
}
